# Generated by Django 2.0.2 on 2018-11-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20181116_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
