# Generated by Django 2.0.2 on 2018-11-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='name',
            field=models.TextField(max_length=100, verbose_name='Nombre'),
        ),
    ]
