# Generated by Django 2.0.2 on 2018-11-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181115_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='name',
            field=models.CharField(max_length=400, verbose_name='Nombre'),
        ),
    ]
